In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [87]:
data=pd.read_csv("Churn_Modelling.csv")

In [88]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [89]:
data=data.drop(columns=['RowNumber','CustomerId','Surname'])

In [90]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [91]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head(8)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1

In [92]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [93]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [94]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [95]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [96]:
data=pd.concat([data.drop(columns=['Geography']),geo_encoded_df],axis=1)

In [97]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [98]:
with open('label_encoder_gender.pkl','wb')as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [99]:
## divide the data
X=data.drop(columns=['Exited'])
y=data['Exited']

In [100]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [101]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test
                        )

In [102]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN implementation

In [103]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [104]:
model=Sequential([Dense(64, activation='relu', input_shape=(X_train.shape[1],)),#hl-1
                  Dense(32 , activation='relu'),#hl-2
                  Dense(1, activation='sigmoid') #output
                  ])

In [105]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [106]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [107]:
# compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [108]:
# setup the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [109]:
# setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [110]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.3995 - accuracy: 0.8317 - val_loss: 0.3453 - val_accuracy: 0.8590
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3577 - accuracy: 0.8576 - val_loss: 0.3393 - val_accuracy: 0.8590
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3456 - accuracy: 0.8584 - val_loss: 0.3423 - val_accuracy: 0.8600
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3435 - accuracy: 0.8612 - val_loss: 0.3377 - val_accuracy: 0.8555
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3404 - accuracy: 0.8621 - val_loss: 0.3495 - val_accuracy: 0.8560
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8635 - val_loss: 0.3419 - val_accuracy: 0.8600
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8625 - val_loss: 0.3385 - val_accuracy: 0.8610
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3366 - accuracy: 0.8611 - val_loss: 0.3381 - val_accuracy: 0.8600
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3330 - accuracy: 0.8645 - val_loss: 0.3409 - val_accuracy: 0.8610
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3303 - accuracy: 0.8640 - val_loss: 0.3598 - val_accuracy: 0.8490
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3287 - accuracy: 0.8627 - val_loss: 0.3399 - val_accuracy: 0.8645
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3254 - accuracy: 0.8639 - val_loss: 0.3458 - val_accuracy: 0.8575
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3251 - accuracy: 0.8670 - val_loss: 0.3398 - val_accuracy: 0.8675
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8687 - val_loss: 0.3430 - val_accuracy: 0.8605

In [111]:
model.save('model.h5')

d:\MYPROJ\DEEPlearning\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [112]:
## load tensorbord extension
%load_ext tensorboard

%tensorboard --logdir logs/fit20260714-223345

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6007 (pid 9280), started 10:38:16 ago. (Use '!kill 9280' to kill it.)

In [113]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [114]:
## load the trained model , scaler pickle ,onehot
model=load_model('model.h5')

# load the encoder and the scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [115]:
# Example input data
input_data= {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [116]:
# One-hot encode 'Geography'
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()

geo_encoded_df= pd.DataFrame(
    geo_encoded,
    columns=label_encoder_geo.get_feature_names_out(['Geography'])
)
geo_encoded_df

d:\MYPROJ\DEEPlearning\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [117]:
print(type(label_encoder_geo))
print(label_encoder_geo)

<class 'sklearn.preprocessing._encoders.OneHotEncoder'>
OneHotEncoder()

In [119]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [120]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [121]:
# combine onehotencoded columns with input data
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)

In [122]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [123]:
# scaling the input data
input_scaled=scaler.transform(input_df)

In [124]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [126]:
#  predict churn
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 36ms/step

array([[0.04280694]], dtype=float32)

In [128]:
prediction_proba=prediction[0][0]
prediction_proba

0.04280694

In [129]:
if prediction_proba>0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn